const mongoose = require("mongoose");

/**
 * Page version schema = @Entity Page Version in Spring Boot = represents history version of a page
 * Fields: page, createdBy, snapshot(title, blocks (with fields type, content, order))
 */
const pageVersionSchema = new mongoose.Schema(
  {
    page: {
      // pageId generated by MongoDB
      type: mongoose.Schema.Types.ObjectId,
      ref: "Page",
      required: true,
    },
    // author
    createdBy: {
      // userId generated by MongoDB
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    // snapshot of the page
    snapshot: {
      // page title
      title: {
        type: String,
        required: true,
      },
      // cover image url
      coverImageUrl: {
        type: String,
        default: "",
      },
      // page icon
      icon: {
        type: String,
        default: "",
      },
      // array list of text blocks
      blocks: [
        {
          blockId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Block",
            required: true,
          },
          type: {
            type: String,
          },
          content: mongoose.Schema.Types.Mixed,
          order: Number,
          // createdBy
          createdBy: {
            // userId generated by MongoDB
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true,
          },
          // updatedBy
          updatedBy: {
            // userId generated by MongoDB
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true,
          },
        },
      ],
    },
    // source of the version
    source: {
      type: String,
      enum: ["MANUAL", "AUTO"],
      default: "MANUAL",
    },
  },
  // automatically generates createdAt and updatedAt
  { timestamps: true },
);

// .index() = speeds up queries that find page version based on page in descending order
pageVersionSchema.index({ page: 1, createdAt: -1 });

// export model
module.exports = mongoose.model("PageVersion", pageVersionSchema);
